namespace Phoenix.Devices.Printers.DatecsMD
{
    using System;

    public enum Message
    {
        AddPaymentSums = 0x31,
        BaudrateDescription = 0x36,
        Cancel = 0x24,
        Cashier = 0x2b,
        CashNum = 30,
        Check = 0x1f,
        CommandNotAllowed = 11,
        CopyByCheck = 0x21,
        Currency = 0x29,
        DeveceNotOpen = 0x11,
        DeviceFriendlyName = 0x2c,
        Discount = 0x26,
        ExellioFriendlyName = 0x30,
        FiscalRamCloseError = 15,
        FiscalRamIsFull = 13,
        FiscalRamReadOnly = 0x10,
        FiscalRamWriteError = 14,
        FP3530T131FriendlyName = 0x34,
        FP3530T20FriendlyName = 0x35,
        FP3530TFriendlyName = 0x2d,
        InvalidCommand = 6,
        LicenseCorrupt = 0x2e,
        NDS = 0x2a,
        No = 0x33,
        NotSupported = 0x1b,
        NullReceipt = 0x1c,
        PaperOut = 12,
        PortTypeCorrupt = 1,
        PrintError = 5,
        PrintRestart = 9,
        RamCleared = 10,
        RamDestroyed = 8,
        ReceiptAlreadyOpen = 0x1d,
        ReceiptNotOpen = 0x22,
        RecivedBadPacket = 4,
        RecivedNAK = 2,
        RecivedUninspected = 0x1a,
        ReciveTimeout = 3,
        Refund = 40,
        RefundByCheck = 0x20,
        Response1 = 0x13,
        Response2 = 20,
        Response3 = 0x15,
        ResponseD = 0x17,
        ResponseE = 0x16,
        ResponseF = 0x12,
        ResponseI = 0x19,
        ResponseR = 0x18,
        SleepAfterPositionPrint = 0x2f,
        SyntaxError = 7,
        TaxCorrupt = 0x23,
        Total = 0x27,
        User = 0x25,
        Yes = 50
    }
}

