//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Devices.Printers.Elicom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CultureStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Devices.Printers.Elicom.CultureStrings", typeof(CultureStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэф. толщины штрихкода.
        /// </summary>
        internal static string BarWidthDescription {
            get {
                return ResourceManager.GetString("BarWidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость.
        /// </summary>
        internal static string BaudrateDescription {
            get {
                return ResourceManager.GetString("BaudrateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КАРТОЧКОЙ.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЛИЧНЫМИ.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассир.
        /// </summary>
        internal static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa Nr. .
        /// </summary>
        internal static string CashNo {
            get {
                return ResourceManager.GetString("CashNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЧЕКОМ.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK..
        /// </summary>
        internal static string CommandError30 {
            get {
                return ResourceManager.GetString("CommandError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command..
        /// </summary>
        internal static string CommandError31 {
            get {
                return ResourceManager.GetString("CommandError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal command..
        /// </summary>
        internal static string CommandError32 {
            get {
                return ResourceManager.GetString("CommandError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z daily report is not zero..
        /// </summary>
        internal static string CommandError33 {
            get {
                return ResourceManager.GetString("CommandError33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error..
        /// </summary>
        internal static string CommandError34 {
            get {
                return ResourceManager.GetString("CommandError34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input registers overflow..
        /// </summary>
        internal static string CommandError35 {
            get {
                return ResourceManager.GetString("CommandError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero input registers..
        /// </summary>
        internal static string CommandError36 {
            get {
                return ResourceManager.GetString("CommandError36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable transaction for correction..
        /// </summary>
        internal static string CommandError37 {
            get {
                return ResourceManager.GetString("CommandError37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient amount on hand..
        /// </summary>
        internal static string CommandError38 {
            get {
                return ResourceManager.GetString("CommandError38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not used..
        /// </summary>
        internal static string CommandError39 {
            get {
                return ResourceManager.GetString("CommandError39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копия чека № .
        /// </summary>
        internal static string CopyNo {
            get {
                return ResourceManager.GetString("CopyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получен некорректный пакет..
        /// </summary>
        internal static string CorruptPacket {
            get {
                return ResourceManager.GetString("CorruptPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КРЕДИТОМ.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупатель: .
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер байта.
        /// </summary>
        internal static string DatabitsDescription {
            get {
                return ResourceManager.GetString("DatabitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  СКИДКА.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ уже открыт..
        /// </summary>
        internal static string DocumentAlreadyOpen {
            get {
                return ResourceManager.GetString("DocumentAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ не был открыт.
        /// </summary>
        internal static string DocumentNotOpen {
            get {
                return ResourceManager.GetString("DocumentNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elicom FP03.
        /// </summary>
        internal static string ElicomFriendlyName {
            get {
                return ResourceManager.GetString("ElicomFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Драйвер не смог установить сеанс связи с принтером..
        /// </summary>
        internal static string EstablishSessionError {
            get {
                return ResourceManager.GetString("EstablishSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аппаратный контроль.
        /// </summary>
        internal static string FlowControlDescription {
            get {
                return ResourceManager.GetString("FlowControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK..
        /// </summary>
        internal static string FPRError30 {
            get {
                return ResourceManager.GetString("FPRError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of paper, printer failure..
        /// </summary>
        internal static string FPRError31 {
            get {
                return ResourceManager.GetString("FPRError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registers overflow..
        /// </summary>
        internal static string FPRError32 {
            get {
                return ResourceManager.GetString("FPRError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock failure or incorrect date&amp;time..
        /// </summary>
        internal static string FPRError33 {
            get {
                return ResourceManager.GetString("FPRError33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened fiscal receipt..
        /// </summary>
        internal static string FPRError34 {
            get {
                return ResourceManager.GetString("FPRError34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment residue account..
        /// </summary>
        internal static string FPRError35 {
            get {
                return ResourceManager.GetString("FPRError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened non-fiscal receipt..
        /// </summary>
        internal static string FPRError36 {
            get {
                return ResourceManager.GetString("FPRError36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered payment but receipt is not closed..
        /// </summary>
        internal static string FPRError37 {
            get {
                return ResourceManager.GetString("FPRError37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal memory failure..
        /// </summary>
        internal static string FPRError38 {
            get {
                return ResourceManager.GetString("FPRError38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        internal static string FPRError39 {
            get {
                return ResourceManager.GetString("FPRError39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing external display..
        /// </summary>
        internal static string FPRError3A {
            get {
                return ResourceManager.GetString("FPRError3A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hours block – missing Z report..
        /// </summary>
        internal static string FPRError3B {
            get {
                return ResourceManager.GetString("FPRError3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overheated printer thermal head..
        /// </summary>
        internal static string FPRError3C {
            get {
                return ResourceManager.GetString("FPRError3C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt power supply in fiscal receipt (one time until status is read)..
        /// </summary>
        internal static string FPRError3D {
            get {
                return ResourceManager.GetString("FPRError3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow EJ..
        /// </summary>
        internal static string FPRError3E {
            get {
                return ResourceManager.GetString("FPRError3E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient conditions..
        /// </summary>
        internal static string FPRError3F {
            get {
                return ResourceManager.GetString("FPRError3F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing external display..
        /// </summary>
        internal static string FPRError41 {
            get {
                return ResourceManager.GetString("FPRError41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hours block – missing Z report..
        /// </summary>
        internal static string FPRError42 {
            get {
                return ResourceManager.GetString("FPRError42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overheated printer thermal head..
        /// </summary>
        internal static string FPRError43 {
            get {
                return ResourceManager.GetString("FPRError43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt power supply in fiscal receipt (one time until status is read)..
        /// </summary>
        internal static string FPRError44 {
            get {
                return ResourceManager.GetString("FPRError44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow EJ..
        /// </summary>
        internal static string FPRError45 {
            get {
                return ResourceManager.GetString("FPRError45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient conditions..
        /// </summary>
        internal static string FPRError46 {
            get {
                return ResourceManager.GetString("FPRError46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функция не поддерживается фискальным принтером.
        /// </summary>
        internal static string FunctionNotSupport {
            get {
                return ResourceManager.GetString("FunctionNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОЛУЧЕНО.
        /// </summary>
        internal static string GetSum {
            get {
                return ResourceManager.GetString("GetSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Механическая ошибка печатающего устройства.
        /// </summary>
        internal static string MechPrintError {
            get {
                return ResourceManager.GetString("MechPrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет связи с принтером чека.
        /// </summary>
        internal static string NoConnectError {
            get {
                return ResourceManager.GetString("NoConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось закрыть чек. Недостаточная сумма для оплаты..
        /// </summary>
        internal static string NotCloseRecNotMoney {
            get {
                return ResourceManager.GetString("NotCloseRecNotMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cec null.
        /// </summary>
        internal static string NullRec {
            get {
                return ResourceManager.GetString("NullRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEC NULL.
        /// </summary>
        internal static string NullReceipt {
            get {
                return ResourceManager.GetString("NullReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет бумаги.
        /// </summary>
        internal static string PaperOutError {
            get {
                return ResourceManager.GetString("PaperOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четность.
        /// </summary>
        internal static string ParityDescription {
            get {
                return ResourceManager.GetString("ParityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный тип порта..
        /// </summary>
        internal static string PortTypeCorrupt {
            get {
                return ResourceManager.GetString("PortTypeCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фискальный принтер не был открыт..
        /// </summary>
        internal static string PrinterNotOpen {
            get {
                return ResourceManager.GetString("PrinterNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принтер не готов к приему комманды..
        /// </summary>
        internal static string PrinterNotReady {
            get {
                return ResourceManager.GetString("PrinterNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный отчет не поддерживается..
        /// </summary>
        internal static string PrintExtReportNotSuport {
            get {
                return ResourceManager.GetString("PrintExtReportNotSuport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать после закрытия.
        /// </summary>
        internal static string PrintingAfterClose {
            get {
                return ResourceManager.GetString("PrintingAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип печати чека.
        /// </summary>
        internal static string PrintingType {
            get {
                return ResourceManager.GetString("PrintingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка протокола..
        /// </summary>
        internal static string ProtocolError {
            get {
                return ResourceManager.GetString("ProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный ответ от принтера..
        /// </summary>
        internal static string RecivedCurruptPacket {
            get {
                return ResourceManager.GetString("RecivedCurruptPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получен отказ от принтера..
        /// </summary>
        internal static string RecivedNAK {
            get {
                return ResourceManager.GetString("RecivedNAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фискальный принтер был занят слишком долго..
        /// </summary>
        internal static string ReciveTimeout {
            get {
                return ResourceManager.GetString("ReciveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат по чеку № .
        /// </summary>
        internal static string RefundByReceipt {
            get {
                return ResourceManager.GetString("RefundByReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чеки возврата не поддерживаютя данным принтером..
        /// </summary>
        internal static string RefundNotSupport {
            get {
                return ResourceManager.GetString("RefundNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный тип отчета не поддерживается..
        /// </summary>
        internal static string ReportTypeNotSupport {
            get {
                return ResourceManager.GetString("ReportTypeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СДАЧА.
        /// </summary>
        internal static string RestSum {
            get {
                return ResourceManager.GetString("RestSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка програмирования налоговых ставок..
        /// </summary>
        internal static string SetTaxError {
            get {
                return ResourceManager.GetString("SetTaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартная печать.
        /// </summary>
        internal static string StandartPrinting {
            get {
                return ResourceManager.GetString("StandartPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоповые биты.
        /// </summary>
        internal static string StopBitsDescription {
            get {
                return ResourceManager.GetString("StopBitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налоговая ставка не поддерживается..
        /// </summary>
        internal static string TaxNotSupport {
            get {
                return ResourceManager.GetString("TaxNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИТОГ.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВСЕГО.
        /// </summary>
        internal static string Total2 {
            get {
                return ResourceManager.GetString("Total2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tremol S/M/FP15-KL(FP15).
        /// </summary>
        internal static string TremolSFriendlyName {
            get {
                return ResourceManager.GetString("TremolSFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось определить модель фискального принтера..
        /// </summary>
        internal static string UnknownDevice {
            get {
                return ResourceManager.GetString("UnknownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный протокол устройства не поддерживается..
        /// </summary>
        internal static string UnknownDeviceProtocol {
            get {
                return ResourceManager.GetString("UnknownDeviceProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не поддерживаемый тип устройства..
        /// </summary>
        internal static string UnknownDeviceType {
            get {
                return ResourceManager.GetString("UnknownDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный тип оплаты не поддерживается..
        /// </summary>
        internal static string UnknownPaymentType {
            get {
                return ResourceManager.GetString("UnknownPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная налоговая группа..
        /// </summary>
        internal static string UnknownTaxGrp {
            get {
                return ResourceManager.GetString("UnknownTaxGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка печати Х-отчета..
        /// </summary>
        internal static string XRepPrintError {
            get {
                return ResourceManager.GetString("XRepPrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятие отчета прервалось.
        /// </summary>
        internal static string ZRepPrintError {
            get {
                return ResourceManager.GetString("ZRepPrintError", resourceCulture);
            }
        }
    }
}
